2022-04-06 01:43:50,077 INFO    MainThread:27454 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/.config/wandb/settings
2022-04-06 01:43:50,077 INFO    MainThread:27454 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/leo/tesis/cloud-classification/code/wandb/settings
2022-04-06 01:43:50,077 INFO    MainThread:27454 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-06 01:43:50,077 INFO    MainThread:27454 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-06 01:43:50,077 INFO    MainThread:27454 [wandb_init.py:_log_setup():405] Logging user logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_014350-3os775c6/logs/debug.log
2022-04-06 01:43:50,078 INFO    MainThread:27454 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_014350-3os775c6/logs/debug-internal.log
2022-04-06 01:43:50,078 INFO    MainThread:27454 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6b953a5580>
2022-04-06 01:43:50,078 INFO    MainThread:27454 [wandb_init.py:init():439] calling init triggers
2022-04-06 01:43:50,078 INFO    MainThread:27454 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'architecture': 'GATConvGNN', 'loss': 'LogeLoss', 'optim': 'SGD', 'dataset': 'GCD', 'builder': 'Cosine Similarity', 'epochs': 15}
2022-04-06 01:43:50,078 INFO    MainThread:27454 [wandb_init.py:init():492] starting backend
2022-04-06 01:43:50,078 INFO    MainThread:27454 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-06 01:43:50,113 INFO    MainThread:27454 [backend.py:ensure_launched():219] starting backend process...
2022-04-06 01:43:50,143 INFO    MainThread:27454 [backend.py:ensure_launched():224] started backend process with pid: 27652
2022-04-06 01:43:50,144 INFO    MainThread:27454 [wandb_init.py:init():501] backend started and connected
2022-04-06 01:43:50,161 INFO    MainThread:27454 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-06 01:43:50,162 INFO    MainThread:27454 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-06 01:43:50,162 INFO    MainThread:27454 [wandb_init.py:init():565] updated telemetry
2022-04-06 01:43:50,242 INFO    MainThread:27454 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-06 01:43:51,094 INFO    MainThread:27454 [wandb_run.py:_on_init():1759] communicating current version
2022-04-06 01:43:51,170 INFO    MainThread:27454 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-06 01:43:51,170 INFO    MainThread:27454 [wandb_init.py:init():625] starting run threads in backend
2022-04-06 01:43:52,687 INFO    MainThread:27454 [wandb_run.py:_console_start():1733] atexit reg
2022-04-06 01:43:52,688 INFO    MainThread:27454 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-06 01:43:52,689 INFO    MainThread:27454 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-06 01:43:52,690 INFO    MainThread:27454 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-06 01:43:52,690 INFO    MainThread:27454 [wandb_init.py:init():664] run started, returning control to user process
2022-04-06 01:43:52,698 INFO    MainThread:27454 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 01:43:52,698 INFO    MainThread:27454 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 01:43:52,732 INFO    MainThread:27454 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 01:43:54,157 INFO    MainThread:27454 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 01:43:54,157 INFO    MainThread:27454 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 01:47:02,559 INFO    MainThread:27454 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-06 01:47:02,561 INFO    MainThread:27454 [wandb_run.py:_restore():1674] restore
2022-04-06 01:47:02,936 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 940
}

2022-04-06 01:47:03,237 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 940
}

2022-04-06 01:47:04,262 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 10489
}

2022-04-06 01:47:04,366 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 10489
}

2022-04-06 01:47:04,469 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 10489
}

2022-04-06 01:47:04,571 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 10489
}

2022-04-06 01:47:04,674 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 940
  total_bytes: 10489
}

2022-04-06 01:47:04,777 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10489
  total_bytes: 10489
}

2022-04-06 01:47:04,881 INFO    MainThread:27454 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10489
  total_bytes: 10489
}

