2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/.config/wandb/settings
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/leo/tesis/cloud-classification/code/wandb/settings
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:_log_setup():405] Logging user logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_142706-3b0rhclk/logs/debug.log
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_142706-3b0rhclk/logs/debug-internal.log
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb5f018b550>
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:init():439] calling init triggers
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'architecture': 'GATConvGNN', 'loss': 'LogeLoss', 'optim': 'SGD', 'dataset': 'GCD', 'builder': 'Fully Connected', 'epochs': 15}
2022-04-06 14:27:06,294 INFO    MainThread:26774 [wandb_init.py:init():492] starting backend
2022-04-06 14:27:06,294 INFO    MainThread:26774 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-06 14:27:06,329 INFO    MainThread:26774 [backend.py:ensure_launched():219] starting backend process...
2022-04-06 14:27:06,359 INFO    MainThread:26774 [backend.py:ensure_launched():224] started backend process with pid: 26818
2022-04-06 14:27:06,360 INFO    MainThread:26774 [wandb_init.py:init():501] backend started and connected
2022-04-06 14:27:06,377 INFO    MainThread:26774 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-06 14:27:06,377 INFO    MainThread:26774 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-06 14:27:06,377 INFO    MainThread:26774 [wandb_init.py:init():565] updated telemetry
2022-04-06 14:27:06,460 INFO    MainThread:26774 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-06 14:27:07,203 INFO    MainThread:26774 [wandb_run.py:_on_init():1759] communicating current version
2022-04-06 14:27:07,382 INFO    MainThread:26774 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-06 14:27:07,382 INFO    MainThread:26774 [wandb_init.py:init():625] starting run threads in backend
2022-04-06 14:27:08,892 INFO    MainThread:26774 [wandb_run.py:_console_start():1733] atexit reg
2022-04-06 14:27:08,893 INFO    MainThread:26774 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-06 14:27:08,894 INFO    MainThread:26774 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-06 14:27:08,895 INFO    MainThread:26774 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-06 14:27:08,896 INFO    MainThread:26774 [wandb_init.py:init():664] run started, returning control to user process
2022-04-06 14:27:08,906 INFO    MainThread:26774 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 14:27:08,906 INFO    MainThread:26774 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 14:27:08,942 INFO    MainThread:26774 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 14:27:10,292 INFO    MainThread:26774 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 14:27:10,292 INFO    MainThread:26774 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 14:27:33,965 INFO    MainThread:26774 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-06 14:27:33,967 INFO    MainThread:26774 [wandb_run.py:_restore():1674] restore
2022-04-06 14:27:34,941 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 938
}

2022-04-06 14:27:35,253 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 938
}

2022-04-06 14:27:35,356 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 10485
}

2022-04-06 14:27:35,460 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 10485
}

2022-04-06 14:27:35,570 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 10485
}

2022-04-06 14:27:35,672 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 938
  total_bytes: 10485
}

2022-04-06 14:27:35,775 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 4002
  total_bytes: 10485
}

2022-04-06 14:27:35,879 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10485
  total_bytes: 10485
}

2022-04-06 14:27:35,983 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10485
  total_bytes: 10485
}

2022-04-06 14:27:36,086 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10485
  total_bytes: 10485
}

2022-04-06 14:27:36,189 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10485
  total_bytes: 10485
}

2022-04-06 14:27:36,292 INFO    MainThread:26774 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 10485
  total_bytes: 10485
}

